language: node_js
sudo: false
node_js:
  - "4.3"
cache:
  directories:
  - node_modules
install:
  - npm install --development
script:
  - npm run lint
  - npm run test
after_script:
  - npm run coveralls
after_success:
  - if [ $TRAVIS_BRANCH == "master" ]; then npm run deploy; fi
