language: node_js
sudo: false
node_js:
  - "4.3"
cache:
  directories:
  - node_modules
install:
  - npm install --development
script:
  - npm run lint
  - npm run test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ $TRAVIS_BRANCH == "master" ]; then npm run deploy; fi
